[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Jyri-Matti L채hteenm채ki"
Model = "Disk storage"
Name = "Disk storage"
SerialNumber = "AA:AA:AA:AA:AA:15"
FirmwareRevision = "100.1.1"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Kes채tila"
ConfiguredName = "Kes채tila"
[services.characteristics.On]
cmd = "cd diskstore; ./cmd/getset.sh summermode"
